o.rc
Knowing who owns the PTY is something I found useful for something else I was playing with. Can probably be cleaned up but works.
Example output:
```
PTY 0 has been idle for 1908696 seconds and is owned by root
PTY 1 has been idle for 321 seconds and is owned by somebody
PTY 2 has been idle for 1 seconds and is owned by root
```
I'm going to try also add some way to have it flag which PTY is *us* because that is useful to know.
=> Updated "getidle" to also show who owns the PTY

o.rc
Now it flags which PTS is us.
```
PTY 0 has been idle for 1910540 seconds and is owned by root 
PTY 1 has been idle for 5 seconds and is owned by root ** this is us **
PTY 2 has been idle for 245 seconds and is owned by somebody
```
=> Added check to getidle to flag which PTY is us

o.rc
++ATH0 for kicking other users off the box, targetted by PTS number. Currently tells them they have segfaulted and kills their SSH process, but this should be refined. Works incredibly reliably. Probably has bugs, so has a big warning.
=> Now with hangup

o.rc
UserKnownHostsFile=/dev/null to prevent known_hosts from snitching, and killed strict hostkey checks for easier sshing.
=> qssh improvements

o.rc
In the getidle function the variable $our_pty was used but the variable was not defined inside o.rc.
A change from [ $our_pty = $i ] to [ "$our_pty" = "$i" ] could fix the errors massage.
Reading the getidle function I found a complex shell code.
I hope the code in awk easier to read and to maintain.
=> getidle rework

README.md, o.rc
If the script was used by "source o.rc" the variable ENV was not defined.
The line "backup=\`cat $ENV\`" was expanded to backup=\`cat \`.
Then the reads from the console, not from the script file.
The patch checks if $ENV is a readable file, then loads the script file into variable backup.
If the script was called in the bash by "source o.rc" then the name of the script is in the variable
BASH_SOURCE. In this case ENV will be set inside o.rc to the file name found in BASH_SOURCE.
The variable ENV was also used in the function getpty.
In the function getpty a check is added to.
Typical ENV contains the relative file name of the script.
Then using ENV after chaning the cwd does not work in the getpty function.
Now the filename in ENV is converted into an absolute file name.
=> Enable to source o.rc. In this case variable ENV is not defined.

o.rc
Replaced a pipeline with four tools cat|grep|awk|tr by a single awk call.
Now cat, grep and tr are not use in this function.
No new tool was included because awk was used before.
=> Replaced a 4 stage pipeline by a single awk call.

o.rc
Replaced a pipeline with four tools awk|sort|cut|tail by a single awk call.
Now sort, cut and tail are not use in this function.
No new tool was included because awk was used before.
Also the equal sign at front of the program names was remove.
The "LONGARG==$(..." seams to be an bug. Now "LONGARG=$" does not prepend a "=" sign to the process name.
The "ps -w" was extended to "ps -ww" from wide output format to unlimited wide output format.
=> replaced 4 stage pipeline by a single awk

o.rc
"if [[ condition ]]" works with bash but is not POSIX, e.g. works not in the dash.
"if [ condition ]" should work with all POSIX shells.
Changed the condition to a string compare because this does not cause an error if the variable is not defined.
=> replaced [[ by POSIX conform [

o.rc
With Ubuntu 18.04LTS the getsuspect function works if o.rc was read with source command in the bash shell.
But the command "ENV=o.rc sh -i" gives an error message:
sh: 190: Syntax error: "(" unexpected
Ubuntu 18.04 has the link “sh → dash”. The sh command starts the dash shell, not the bash shell.
The changed code works with bash and dash shell on Ubuntu 18.04 LTS.
=> fixed syntax error message after 'ENV=or.c sh -i' call on Ubuntu 18.04

o.rc
Avoids hostkey checking or logging new hostkeys for forensics reasons
=> alias ssh now uses the extra options from qssh

o.rc
less, wget, vim and mysql all snitch. These SHOULD kill the snitching, but I need to run some tests and may alter these later (especially the ones that involve environmental variables).
Partly deals with https://github.com/zMarch/Orc/issues/16 but there is more to be done!
=> Killed some snitching

o.rc
Bug fix:
- Some files were written into directory "." and into "$OUTP".
Additions:
- The $EUID is defined in the bash but not in the dash. Comparing the effective UID with the UID of the /root directory works in the dash and in the bash. The combination of both checks could work on other shells also.
- Saves stdout and stderr output of the called programs into files. In some cases the error messages could be also useful.
- Creates a log file with entries: basename of the saved outputs and the called program with parameters. To analyze the stored files later, after o.rc changes, the used program parameters could by helpful.
- If xz compression is not available then fallback to gzip compression of the tar file was added.
=> Getinfo fix

o.rc
Bug fix: The getidle function uses the gawk function systime. Now systime inside awk is replaced by calling date in the shell. This should be work with POSIX conform awk implementation.
=> Bug fix: remove gawk function systime.

o.rc
The `if $1==ENVIRON["our_pty"]` check was always returning false, due to the global "our_pty" not being set. This fixes it, but can probably be done better than my `tty | cut -d '/' -f 4` which is probably gonna break horribly somehow.
Before:
```
PTY 0 is 3 seconds idle and owned by root
```
After:
```
PTY 0 is 6 seconds idle and owned by root ** this is us **
#
```
=> Fix missing global our_pty variable in getidle()

o.rc
Minor bug fix:
- The getusers function never lists a user like 'falser' (A real name, you can find persons with this name) because the grep filters 'false' in the whole passwd line. The new awk based function filters only the shell names.
Optimization:
- The common code part in getusers and getuservice functions were moved into a new listusers function.
- The very long pipe in the getuservice function with grep, awk and sed was replaced by a short awk code. I hope this code is easier to read and maintain.
The new code was checked with awk, awk --posix and mawk on Ubuntu 10.04LTS and on Debian 9.
=> getusers and getuservices optimization

o.rc
Add some checks in the hangup function:
- One argument must be given.
- The user must be available. E.g. if the argument is not at valid PTS number than this abort stops the function.
- The pid must be available. E.g. if the PTS is not connected via a sshd than this check abort the function.
=> Add some checks in hangup function

o.rc
The function uses curl, wget, perl or python.
The function is stored in a prepared "compatibility layer" section of the file. More functions like this to handle system differences will be added in this section.
=> Add function to load https URL

o.rc
- Bugfix: qsu and qssh create a shell script file to echoing the password. If the password contains special letters, e.g. test$1, then the password must be set in single quotes.
- Compatibility: the generated script file will work with each sh. The bash is possible but not a must have.
- Optimization: Added some checks for missing arguments
- Optimization: Sets the generated script files read/write/execute rights only for the user, not for all. I suppose reading the password is better limited. I hope no system needs wide access rights for the SUDO_ASKPASS command file.
=> Password echo in quotes

o.rc
- Increases the portability if the portscan function: Now bash, nmap, python (version 2) or nc (netcat) are used. Hence if o.rc runs in a POSIX shell on a system without bash a portscan may be possible with one of the other tools.
- The TCP connection check is isolated in a function orc_tryTcpConnection. This function may be used later to check the connection in other functions, see issue #43.
=> Portscan tools

o.rc
According to issue #43: curl, wget, perl library and python library read environment variables to configure http and https proxy. But the current curl uses upper case letters and the current wget uses lower case letters. (Found in the man pages.) The perl library could have changed the writing in the history. (Found different information on web pages.)
To support all tools in all versions HTTP(S)_PROXY and http(s)_proxy exports are added in the orc_loadURL function.
On Ubuntu 18.0.4 all four download tools work with this export definitions in a test.
=> add HTTP(S)_PROXY and http(s)_proxy exports

o.rc
According issue #43: try TCP connection to github before load and run the scripts.
Does not abort the function. Only a message is given if https_proxy is not defined and TCP connection is not possible.
The penalty is the time for an additional TCP open connection for each script load & start.
=> add TCP connection check before script load and run

o.rc
Bugfix
* getidle function was not running. I quoted wrongly the stat argument. Now it works again.
Minor bugfix
* NHOME could contain a wrong name if grep finds the current user id in a group-id or phone number.
Clean up
* moved some helper functions to the help function section.
* removed log2outp function, this function should be moved to orc_log2outp but was copied.
=> bugfix in getidle and $NHOME

o.rc
Only the first part of getnet:
* list addresses in the ARP cache
If another will use the code, then this pull request could be merged immediately. Hence I do not create a draft pull request. If the code is not needed yet, then I will add more commits into this pull request and the request could be **merged later.**
orc_filterIpAddress greps IPv4 and hopefully IPv6 addresses out of the stdout stream. Here it is used to filter the ARP table outputs.
I will add more functions into getnet2 until it is a replacement for the getnet function.
=> getnet rework

o.rc
A check for a program or shell command could be executed by a hash or a type command. The hash command works in the bash and dash but not in the ksh. The type command works in bash, dash and ksh but is not POSIX conform.
So try to figure out which command works and define an alias to the command.
=> add selection of hash or type command

.travis.yml, o.rc
- orc_lastIP4Integer was broken in shells with 64-bit integers, was working with 32-bit integers only. The bug should be fixed.
- Some shellcheck findings are removed. The code should be more portable to other shell interpreters now.
- Add static code check with the shellcheck tool for the shell scripts in the resources sub-directory.
=> fixed getnet and some shellcheck findings

o.rc, tests/run_shunit2_int.sh, tests/run_shunit2_user.sh, tests/scripts_included.sh, tests/start_shunit2.sh
Now all "rm" command are called with "-f" (force) switch.
The "-f" should prevent any prompt.
Beside: Bug fix: "exit" and not "return" to leave scripts, some typos.
=> add missing -f switch for rm cmds
